<?php
namespace ProcessWire;

class WesanoxMenuBuilder extends WireData implements Module
{
public static function getModuleInfo()
    {
        return array(
            'title' => 'wesanox Menu Builder',
            'summary' => 'A little Menu Builder for Processwire.',
            'version' => '0.0.4',
            'author' => 'André Wester',
            'icon' => 'codepen',
            'singular' => true,
            'autoload' => true,
            'installs' => ['CroppableImage3'],
            'requires' => array(
                'ProcessWire>=3.0.210',
                'PHP>=8.0.0',
                'FieldtypeRepeaterMatrix>=0.0.9',
                'WesanoxHelperFields>=0.0.1',
                'WesanoxHelperClasses>=0.0.1',
            ),
        );
    }

    protected array $externalModules = [
        'CroppableImage3' => 'https://github.com/horst-n/CroppableImage3/archive/master.zip',
    ];

    protected array $external_modules = [
        'WesanoxHelperFields' => 'https://github.com/wesanox/WesanoxHelperFields/archive/refs/heads/main.zip',
        'WesanoxHelperClasses' => 'https://github.com/wesanox/WesanoxHelperClasses/archive/refs/heads/main.zip',
    ];

    /**
     * @var Module|_Module|null $helper_classes
     * @var Module|_Module|null $helper_fields
     */
    protected Module|_Module|null $helper_fields;
    protected Module|_Module|null $helper_classes;

    /**
     * @var array $fields_array
     */
    protected array $fields_array = [];

    /**
     * @var string $template_options
     */
    protected string $template_options = 'options_generals';

    /**
     * @throws WirePermissionException
     */
    function __construct()
    {
        parent::__construct();

        $this->helper_classes = $this->modules->get('WesanoxHelperClasses');
        $this->helper_fields = $this->modules->get('WesanoxHelperFields');

        $this->fields_array = include $this->config->paths->WesanoxMenuBuilder . 'config/fields.php';
    }

    /**
     * init function to get save hook for the options-page
     *
     * @return void
     */
    public function init() :void
    {
        wire()->addHookAfter('Pages::saved', $this, 'saveMenuInt');
    }

    /**
     * install function for the modul
     *
     * @return void
     * @throws WireException
     * @throws WirePermissionException
     */
    public function ___install() :void
    {
        /**
         * Install internal modules
         */
        foreach ($this->internal_modules as $module_name) {
            if (!$this->modules->isInstalled($module_name)) {
                $this->modules->get($module_name);
            }
        }

        /**
         * Install external modules
         */
        foreach ($this->external_modules as $module_name => $module_url) {
            if (!$this->modules->isInstalled($module_name)) {
                $message = $this->helper_classes->downloadInstall($module_name, $module_url);
                if ($message !== true) $this->error($message);
            }
        }

        /**
         * create fields
         */
        foreach ($this->fields_array as $field_array) {
            $this->helper_fields->createFields($field_array);
        }

        /**
         * if not exists, create settings Page or add new Fields
         * to the settingspage
         */
        if ( !$this->templates->get($this->template_options) ) {
            $fg = new Fieldgroup();
            $fg->name = $this->template_options;
            $fg->add('title');
            $fg->add('tab_menu');
            $fg->add('matrix_menu');
            $fg->add('tab_menu_END');
            $fg->save();

            $t = new Template();
            $t->name = $this->template_options;
            $t->label = 'Einstellungen';
            $t->fieldgroup = $fg;
            $t->icon = 'cogs';
            $t->tags = 'Options';
            $t->noParents = -1;
            $t->save();

            if (!$this->pages->get('template=options_generals')->id) {
                $p = new Page();
                $p->template = 'options_generals';
                $p->parent = $this->pages->get(1);
                $p->title = 'Einstellungen';
                $p->name = 'settings';
                $p->save();
            }
        } else {
            $t = $this->fieldgroups->get($this->template_options);
            $t->add('tab_menu');
            $t->add('matrix_menu');
            $t->add('tab_menu_END');
            $t->save();
        }
    }

    /**
     * uninstall the modul with the fields
     *
     * @return void
     * @throws WireException
     */
    public function ___uninstall(): void
    {
        /**
         * remove fields from option page
         */
        if($this->templates->get($this->template_options)) {
            $t = $this->fieldgroups->get($this->template_options);
            $t->deleteAll();
            $t->save();
        }

        /**
         * delete fields
         */
        $matrix_menu = $this->fields->get('matrix_menu');
        $this->fields->delete($matrix_menu);

        $this->helper_fields->deleteFields($this->fields_array);
    }

    /**
     * get an id for the menu items and sub menu
     *
     * @param HookEvent $event
     * @return void
     */
    public function saveMenuInt(HookEvent $event) :void
    {
        $page = $event->arguments(0);

        $id = $this->pages->get("template=options_generals")->id;

        if ($page->id === $id) {
            foreach ($page->matrix_menu as $matrix) {
                $i = 0;
                $j = 0;

                foreach ($matrix->repeater_menu as $key => $repeater) {
                    if ($repeater->depth === 0) {
                        $i++;
                    }

                    if ($repeater->depth === 1) {
                        $j = $key * 256;
                    }

                    $repeater->of(false);
                    $repeater->int_menu = $i;
                    $repeater->int_menu_sub = $j;
                    $repeater->save();
                }
            }
        }
    }

    /**
     * function to get an array from the repeater element inside the matrix
     *
     * @param RepeaterMatrixPageArray $menu_items
     * @param int $menu_position
     * @return string
     */
    public function renderMenu ( RepeaterMatrixPageArray $menu_items, int $menu_position = 0 ) : string
    {
        $menu           = [];
        $menu_sub       = [];
        $menu_sub_sub   = [];

        foreach ($menu_items as $item) {
            if (!$item->select_menu_position || $item->select_menu_position->id != $menu_position) {
                continue;
            }

            $position = $item->select_menu_position->title;

            if (!isset($menu[$position])) {
                $menu = [
                    'position' => $position,
                    'menu_elements' => [],
                ];
            }

            foreach ($item->repeater_menu as $menu_item) {
                $depth = $menu_item->depth;

                if ( $depth === 2 ) {
                    $menu_sub_sub_element = [
                        'url' => $menu_item->link_extern ?: ($menu_item->link_intern->url ?? ''),
                        'title' => $menu_item->link_text ?: ($menu_item->link_intern->title ?? 'KEIN TITEL'),
                        'id' => $menu_item->link_intern->id ?? 0,
                        'aria' => $menu_item->link_aria ?: ($menu_item->link_intern->title ?? 'KEIN ARIA LABEL'),
                        'desc' => $menu_item->link_description ?: '',
                        'image' => $menu_item->image->url ?? '',
                        'parent_id' => $menu_item->int_menu_sub,
                        'target' => $menu_item->link_new_tab,
                        'sub_menu_id' => $menu_item->int_menu_sub,
                    ];

                    $menu_sub_sub[] = $menu_sub_sub_element;
                }
            }

            foreach ($item->repeater_menu as $menu_item) {
                $depth = $menu_item->depth;

                if ( $depth === 1 ) {
                    $menu_sub_element = [
                        'url' => $menu_item->link_extern ?: ($menu_item->link_intern->url ?? ''),
                        'title' => $menu_item->link_text ?: ($menu_item->link_intern->title ?? 'KEIN TITEL'),
                        'id' => $menu_item->link_intern->id ?? 0,
                        'aria' => $menu_item->link_aria ?: ($menu_item->link_intern->title ?? 'KEIN ARIA LABEL'),
                        'desc' => $menu_item->link_description ?: '',
                        'image' => $menu_item->image->url ?? '',
                        'parent_id' => $menu_item->int_menu,
                        'target' => $menu_item->link_new_tab,
                        'sub_menu_id' => $menu_item->int_menu_sub,
                        'menu_sub_sub_elements' => [],
                    ];

                    foreach ( $menu_sub_sub AS $sub ) {
                        if ($sub['parent_id'] == $menu_item->int_menu_sub) {
                            $menu_sub_element['menu_sub_sub_elements'][] = $sub;
                        }
                    }

                    $menu_sub[] = $menu_sub_element;
                }
            }

            foreach ($item->repeater_menu as $menu_item) {
                $depth = $menu_item->depth;

                if ( $depth === 0 ) {
                    $menu_element = [
                        'url' => $menu_item->link_extern ?: ($menu_item->link_intern->url ?? ''),
                        'title' => $menu_item->link_text ?: ($menu_item->link_intern->title ?? 'KEIN TITEL'),
                        'id' => $menu_item->link_intern->id ?? 0,
                        'aria' => $menu_item->link_aria ?: ($menu_item->link_intern->title ?? 'KEIN ARIA LABEL'),
                        'desc' => $menu_item->link_description ?: '',
                        'image' => $menu_item->image->url ?? '',
                        'parent_id' => $menu_item->int_menu,
                        'target' => $menu_item->link_new_tab,
                        'menu_sub_elements' => [],
                    ];

                    foreach ( $menu_sub AS $sub ) {
                        if ($sub['parent_id'] == $menu_item->int_menu) {
                            $menu_element['menu_sub_elements'][] = $sub;
                        }
                    }

                    $menu['menu_elements'][] = $menu_element;
                }
            }
        }

        return json_encode($menu);
    }
}